//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RessetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDb 
    {
        public string Name { get; set; }
        public string father_median_name { get; set; }
        public string primary_school_name { get; set; }
        public string mother_s_day_of_birth { get; set; }
        public string password { get; set; }
    }
}
